# 📘 Linear Algebra + NumPy Practice Notebook

Goal: Connect **Math → Code → ML intuition**

## 🧠 Instructions
- First implement manually (loops)
- Then use NumPy built-ins
- Compare results
- Add your own test cases

## 🔹 1. Dot Product

In [ ]:
# TODO: Implement dot product manually
def dot_manual(a, b):
    return  sum(a[i]*b[i] for i in range(len(a)))# sum of product of individual elements 
#necessary condition len(a)==len(b)

# Test
a = [1,2,3]
b = [4,5,6]
print(dot_manual(a,b))

32


In [3]:
# NumPy version
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


## 🔹 2. Vector Norm

In [5]:
# TODO: Implement norm manually
def norm_manual_l2(v):
    return sum(v[i]**2 for i in range(len(v))) # l2 norm

def norm_manual_l1(v):
    return sum(abs(v[i]) for i in range(len(v))) 

print(norm_manual_l1([3,4,12,-3]))
print(norm_manual_l2([-2,-4,-5]))

22
45


In [ ]:
# NumPy
v = np.array([3,4])
print(np.linalg.norm(v))

## 🔹 3. Projection

In [ ]:
# TODO: Implement projection
def projection(v, u):
    num_=sum (v[i]*u[i] for i in range(len(v)))
    denom_=sum(u[i]**2 for i in range(len(u)))
    res = [float(num_/denom_ * u[i]) for i in range(len(u))]
    return res

v = np.array([3,4])
u = np.array([1,0])
print(projection(v,u))

[3.0, 0.0]


In [30]:
def projection(v, u):
    if len(v) != len(u):
        raise ValueError("Vectors must have same dimension")

    denom = sum(x*x for x in u)
    if denom == 0:
        raise ValueError("Cannot project onto zero vector")

    num = sum(a*b for a, b in zip(v, u))

    return [(num / denom) * x for x in u]

v = np.array([3,4])
u = np.array([1,0])
print(projection(v,u))

[np.float64(3.0), np.float64(0.0)]


In [8]:
# NumPy reference
def projection_np(v,u):
    return (np.dot(v,u)/np.dot(u,u))*u

print(projection_np(v,u))

[3. 0.]


## 🔹 4. Eigenvalues & Eigenvectors

In [6]:
# Use NumPy first
A = np.array([[2,0],[0,3]])
vals, vecs = np.linalg.eig(A)
print(vals)
print(vecs)

[2. 3.]
[[1. 0.]
 [0. 1.]]


# TODO:
- Verify eigen equation: A v = λ v

In [24]:
Av = A@vecs[0]
λv = vals*vecs[0]
print(Av)
print(λv)
print(Av==λv)

[2. 0.]
[2. 0.]
[ True  True]


## 🔹 5. SVD

In [25]:
A = np.array([[1,2],[3,4]])
U,S,Vt = np.linalg.svd(A)
print(U)
print(S)
print(Vt)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


# TODO:
- Reconstruct matrix using U, S, Vt

In [28]:
# Reconstruction
S_mat = np.zeros((U.shape[0], Vt.shape[0]))
np.fill_diagonal(S_mat, S)
A_recon = U @ S_mat @ Vt
print(A_recon)

[[1. 2.]
 [3. 4.]]


## 🔹 6. Low Rank Approximation

In [29]:
# TODO: keep only top k singular values
k = 1
S_k = np.zeros((U.shape[0], Vt.shape[0]))
S_k[:k,:k] = np.diag(S[:k])
A_k = U @ S_k @ Vt
print(A_k)

[[1.27357371 1.80720735]
 [2.87897923 4.08528566]]
